### ISSUE TITLE
I can't connect to the cameras

### ISSUE THREAD

**Issue by carlosesfra** [HarlemSquirrel/python-vivotek#7]
Hi guys
I'm trying to use your scripts but I can't do a connection with the camera. I need to take snapshots but I received this error:

HTTPSConnectionPool(host='10.224.234.214', port=443): Max retries exceeded with url: /cgi-bin/viewer/video.jpg?quality=3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179D23A83C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

I'm watching the cameras on a web browser, and I try with all the different ports availables on the configuration.

**Comment by HarlemSquirrel** [comment]
Hi carlosesfra, is your camera configured for SSL? Are you using HTTPS in the browser?

**Comment by carlosesfra** [comment]
Hi Harlem

At the end I solved the problem using a GET method from Vivotek.
I save the image on a folder with the datetime

This is the code:

#%% 
import time
import requests
from datetime import datetime

#%% Using HTTP GET

host = 'http://<ip camera>/cgi-bin/viewer/video.jpg'
user = 'root'
passw = '<password>'
SavePicPath = 'E:/Fot_vivotek/' # path where I save the images

r = requests.get(host, auth = (user, passw))
if r.status_code == 200:
    now = datetime.now()
    dt_str=now.strftime("%Y%m%d_%H%M%S")
    namepic = dt_str + '.jpg'
    img_path = SavePicPath + namepic
    with open(img_path,'wb') as f:
        f.write(r.content)
else:
    print('the image was not captured')

**Comment by HarlemSquirrel** [comment]
Are you running this code from the camera itself? That's not using SSL which may mean SSL is not configured in the camera.

**Comment by HarlemSquirrel** [comment]
@carlosesfra are you still having this issue?

**Comment by HarlemSquirrel** [comment]
Let me know if this is still happening
